//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Stations struct {
	ID          uuid.UUID `sql:"primary_key"`
	ExternalUID *string
	Public      bool
	Title       *string
	Description *string
	Address     *string
	Latitude    *float64
	Longitude   *float64
}
